project:
  type: website
  output-dir: docs

website:
  title: "Hiring CV Bias"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Problem Statement"
        href: pages/01-problem.html
      - text: "Pipeline"
        href: pages/02-pipeline.html
      - text: "Results"
        href: pages/03-results.html

format:
  html:
    theme: journal
    toc: true
    toc-depth: 2

exclude:
  - data/
  - "*.ipynb"
  - "__pycache__/"
